// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsRoaCSzLa8xueCkangCJDZV45AddEPmQ',
    appId: '1:359521917625:web:1857b9702753d1304fd968',
    messagingSenderId: '359521917625',
    projectId: 'task-management-apps-3dda2',
    authDomain: 'task-management-apps-3dda2.firebaseapp.com',
    storageBucket: 'task-management-apps-3dda2.appspot.com',
    measurementId: 'G-NWH4PLM3HY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI_dDSQiH6rUBLo5mxTrjes4ovpFc6fkI',
    appId: '1:359521917625:android:5c97edbff5b1040f4fd968',
    messagingSenderId: '359521917625',
    projectId: 'task-management-apps-3dda2',
    storageBucket: 'task-management-apps-3dda2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZze3oZKsWa4I8Iwh-AxLRUg9gJcx6FW8',
    appId: '1:359521917625:ios:8af6484c4e6d7fab4fd968',
    messagingSenderId: '359521917625',
    projectId: 'task-management-apps-3dda2',
    storageBucket: 'task-management-apps-3dda2.appspot.com',
    androidClientId: '359521917625-9afukbj7n115k8dkn1gncgpn5upqekk0.apps.googleusercontent.com',
    iosClientId: '359521917625-banocsam4950ha0ruqggofc00r5hckni.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZze3oZKsWa4I8Iwh-AxLRUg9gJcx6FW8',
    appId: '1:359521917625:ios:8af6484c4e6d7fab4fd968',
    messagingSenderId: '359521917625',
    projectId: 'task-management-apps-3dda2',
    storageBucket: 'task-management-apps-3dda2.appspot.com',
    androidClientId: '359521917625-9afukbj7n115k8dkn1gncgpn5upqekk0.apps.googleusercontent.com',
    iosClientId: '359521917625-banocsam4950ha0ruqggofc00r5hckni.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManagementApp',
  );
}
